### PR TITLE
Update to VMA 3.0.1, update crate version to 0.3.0

### PR DESCRIPTION
**Pull request by joshuagiles**
Hi,

This crate merged a PR recently which made the project point to a custom (outdated) fork of VMA with unreviewed changes in the API. As a step in updating to the latest tagged release of VMA, that change has been reverted.

The same PR included another commit ("Foo bar") which changed AllocatorCreateInfo::new to take Rc<Deref<Target=Instance|Device>> instead of simply Deref. This change broke the tests, and also eliminated the benefit of taking references to Instance and Device in the first place, because a clone now must be made to place in the Rc. That change has also been reverted (which greened the existing tests).

Several other commits were included in the PR from another github user @Neo-Zhixing who rightfully protested that their changes were merged without review and without informing them. After reviewing the remaining changes after the above reversions, I opted not to revert all of those changes as they seem rather benign and/or desirable, like correctly tagging deprecated enum variants and replacing magic numbers with constants from the FFI binding. I hope they will provide a comment noting that this is alright with them, and noting any changes I might have missed that should still be reverted, before this PR is merged.

VMA 3.0.0 added a new feature: a virtual allocator for using the same VMA algorithms without allocating actual backing memory. It doesn't require an Allocator to be created, just a VmaVirtualBlock object which takes a capacity value, then multiple VmaVirtualAllocation of any size may be allocated and freed from the VmaVirtualBlock, to obtain allocated offsets. Possible use cases include allocating sub-regions of a buffer, managing allocations of non-GPU memory, or even non-graphics related block allocation purposes.

This PR adds wrapping for the new VmaVirtualBlock and VmaVirtualAllocation objects, and tests for the newly added wrappers, to maintain feature parity with the VMA version used for the binding. I needed this particular feature for my own purposes and I'm sure other vk_mem users will be happy to have access to it as well.

Thanks,
    Josh

### CODE REVIEW

**Comment by Neo-Zhixing** [comment]
Thank you @joshuagiles 
I would recommend that we contact the repository owner and see what can be done.

**Comment by MarijnS95** [comment]
Maybe also ping @cheako to ask what the plan was with https://github.com/gwihlidal/vk-mem-rs/pull/62? Quoting the PR description:

> This wasn't useful for me, perhaps it'll be useful for some?

Is a really poor reason to open a PR _with someone else's_ changes :disappointed:

**Comment by cheako** [comment]
Yeah, I'm not sure how the PR got to be that way, perhaps I just didn't look closely enough at what I was pushing.  Either way I think it was always supposed to be a throw away PR...  I should have shared links to those commits in a regular issue.

Also isn't `AsRef` and not `Deref` the way to implement what I was trying to do, never look at your old code.

**Comment by Neo-Zhixing** [comment]
@joshuagiles

Another problem I have spotted in commit 3b2ac31:

You shouldn't need a lifetime parameter on `AllocatorCreateInfo`. With Device and Instance being generic, it should now have their own lifetimes.

**Comment by aloucks** [comment]
I'm hesitant to even comment as it may be considered rude, but that PR should have never been merged.

**Pull request merged**
